export const categoryStrings = [ "AR", "BR", "LMG", "SMG", "Shotgun", "Sidearm", "Sniper", "Weird" ] as const;

export const filterPropStrings = [ // Sorted by text
  "Burst",
  "DPS",
  "DPS End",
  "Damage End",
  "Damage Start",
  "Detection Radius",
  "Equip Time",
  "Fire Rate",
  "Health",
  "Magazine Size",
  "Pellets",
  "DropoffStuds End",
  "DropoffStuds Start",
  "Recoil Aim",
  "Recoil Hip",
  "Reload Time",
  "Speed",
  "Spread Aim",
  "Spread Hip",
  "TTK",
  "TTK End",
  "Time To Aim",
  "TTE"
] as const;

export const propertyStrings = [ // Sorted by order of how I want it to show up in the part list
  "Damage",
  "Damage Start",
  "Damage End",
  "DropoffStuds",
  "DropoffStuds Start",
  "DropoffStuds End",
  "Pellets",
  "Fire Rate",
  "Spread Aim",
  "Spread Hip",
  "Detection Radius",
  "Equip Time",
  "Magazine Size",
  "Reload Time",
  "Recoil Aim",
  "Recoil Hip",
  "Health",
  "Speed",
  "Burst",
  "Time To Aim",
  "TTK",
  "TTK End",
  "DPS",
  "DPS End",
  "TTE"
] as const

// I tried going [...].sort() but I lose the const assertation so gonna have to just hard code this :/
export const filterTitles = [
  "Ban Barrel",
  "Ban Core",
  "Ban Grip",
  "Ban Magazine",
  "Ban Stock",
  "Burst",
  "Categories",
  "DPS",
  "DPS End",
  "Damage End",
  "Damage Start",
  "Detection Radius",
  "DropoffStuds End",
  "DropoffStuds Start",
  "Equip Time",
  "Fire Rate",
  "Force Barrel",
  "Force Core",
  "Force Grip",
  "Force Magazine",
  "Force Stock",
  "Health",
  "Magazine Size",
  "Pellets",
  "Recoil Aim",
  "Recoil Hip",
  "Reload Time",
  "Sort Type",
  "Speed",
  "Spread Aim",
  "Spread Hip",
  "TTK",
  "TTK End",
  "Time To Aim",
  "Time To Empty",
  "Total Results"
] as const;

export const filterDescriptions: {[key in typeof filterTitles[number]]: string} = {
  "Ban Barrel": "Ban the calculator from using a list of barrels",
  "Ban Core": "Ban the calculator from using a list of cores",
  "Ban Grip": "Ban the calculator from using a list of grips",
  "Ban Magazine": "Ban the calculator from using a list of magazines",
  "Ban Stock": "Ban the calculator from using a list of stocks",
  "Burst": "Burst range to filter",
  "Categories": "Categories to include in the calculation",
  "DPS": "Damage per second",
  "DPS End": "Damage per second using the ending damage",  
  "Damage End": "Total ending damage (not per pellet)",
  "Damage Start": "Total starting damage (not per pellet)",
  "Detection Radius": "Dectection radius",
  "Equip Time": "Equip time in seconds",
  "Fire Rate": "Fire rate in rounds per minute",
  "Force Barrel": "Force the calculator to use a list of barrels",
  "Force Core": "Force the calculator to use a list of cores",
  "Force Grip": "Force the calculator to use a list of grips",
  "Force Magazine": "Force the calculator to use a list of magazines",
  "Force Stock": "Force the calculator to use a list of stocks",
  "Health": "Health boost percentage",
  "Magazine Size": "Magazine size",
  "Pellets": "Pellet count",
  "DropoffStuds End": "Dropoff studs ending range",
  "DropoffStuds Start": "Dropoff studs starting range",
  "Recoil Aim": "Vertical ending recoil aiming",
  "Recoil Hip": "Vertical ending recoil hipfire",
  "Reload Time": "Reload time in seconds",
  "Sort Type": "The property and priority to sort the results by",
  "Speed": "Movement speed percentage",
  "Spread Aim": "Aiming spread",
  "Spread Hip": "Hipfire spread",
  "TTK": "Time to kill in seconds",
  "TTK End": "Time to kill in seconds using the ending damage",  
  "Time To Aim": "Time to aim in seconds",
  "Time To Empty": "Total time to empty the magazine in seconds",
  "Total Results": "Number of top guns to display"
};

export const numberRangeOptions = ['min', 'max', 'from'] as const;
export const sortTypeOptions = ['Auto', 'Highest First', 'Lowest First'] as const;
